# Generated by Django 4.2.9 on 2025-01-15 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("FOLLOW", "Follow"),
                            ("LIKE", "Like"),
                            ("COMMENT", "Comment"),
                            ("MESSAGE", "Message"),
                            ("MENTION", "Mention"),
                            ("GROUP_INVITE", "Group Invite"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("related_object_id", models.UUIDField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
