# Generated by Django 4.2.9 on 2025-02-05 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_message_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="online_participants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users online in this chat room",
                related_name="online_chat_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
